<%@ Page Title="" Language="C#" MasterPageFile="~/AdminTool/MasterPages/admin.master" AutoEventWireup="true" CodeFile="Center-Manage-Testimonials.aspx.cs" Inherits="AdminTool_Templates_Center_Manage_Testimonials" %>

<asp:Content ID="Content2" ContentPlaceHolderID="mainCPH" runat="Server">
    <style type="text/css">
        .hiddenCareerColumn {
            display: none;
        }

        table th:nth-child(7) {
            display: none;
        }
    </style>
    <div id="centerInfo" runat="server" visible="false">
            <strong>Name: </strong> <asp:Label ID="lblCenterName" runat="server" /> &nbsp;&nbsp; <strong>Center Id: </strong><asp:Label ID="lblCenterId" runat="server" />
        </div>
    <h3 align="left">Manage Testimonials&nbsp;</h3>
    <p align="left">This&nbsp;section&nbsp;enables&nbsp;you to&nbsp;add&nbsp;and manage the&nbsp;testimonials on your website.</p>
    <ol>
        <li>
            <div align="left">
                To add a new testimonial.<br />
                <ol>
                    <li>Click on the Add&nbsp;Testimonials link.</li>
                    <li>Type or copy from another editor the new testimonial.</li>
                    <li>Enter the customer's First Name, Last Name, Title, and Company.</li>
                    <li>Click on Submit to complete the configuration.<br />
                    </li>
                </ol>
            </div>
        </li>
        <li>
            <div align="left">To edit an existing testimonial, click on the Title link.<br/></div>
        </li>
        <li>To delete an existing testimonial, click on the delete link.</li>
    </ol>
    <a href="/AdminTool/Templates/AddTestimonial.aspx">Add Testimonial</a>
    <br />
    <br />
    <asp:GridView ID="GridView1" HeaderStyle-BackColor="#6A6A6A" HeaderStyle-ForeColor="#FE9901"
        RowStyle-BackColor="#EDEDED" AlternatingRowStyle-BackColor="White" AlternatingRowStyle-ForeColor="#000"
        runat="server" AutoGenerateDeleteButton="false" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="false" AllowPaging="false" >
        <Columns>
            <asp:HyperLinkField DataTextField="Title" DataNavigateUrlFields="TestimonialId"
                DataNavigateUrlFormatString="/AdminTool/Templates/AddTestimonial.aspx?id={0}" HeaderText="Title" HeaderStyle-Width="150px" />
            <asp:BoundField DataField="FirstName" HeaderText="First Name" HeaderStyle-Width="150px" />
            <asp:BoundField DataField="LastName" HeaderText="Last Name" HeaderStyle-Width="150px" />
            <asp:BoundField DataField="Organization" HeaderText="Company" HeaderStyle-Width="150px" />
            <asp:BoundField DataField="Created_Date" HeaderText="Created Date" HeaderStyle-Width="150px" />
            <asp:BoundField DataField="TestimonialId" ItemStyle-CssClass="hiddenCareerColumn" HeaderText="" HeaderStyle-Width="150px" />
            <asp:CommandField ShowDeleteButton="True" /> 
        </Columns>
        <EmptyDataTemplate>
            <table cellspacing="0" rules="all" border="0" style="border-collapse: collapse;">
                <tr style="color: White; background-color: #6A6A6A;">
                    <th scope="col" style="width: 150px;">Title</th>
                    <th scope="col" style="width: 150px;">First Name</th>
                    <th scope="col" style="width: 150px;">Last Name</th>
                    <th scope="col" style="width: 150px;">Company</th>
                    <th scope="col" style="width: 150px;">Created Date</th>
                </tr>
                <tr>
                    <td colspan="99" align="center">No records found for the search criteria.</td>
                </tr>
            </table>
        </EmptyDataTemplate>
    </asp:GridView>
    <asp:HiddenField ID="hddnCenterId" runat="server" Value="" />
</asp:Content>

