define({
    'Search': 'Rechercher',
    'LastModified': 'Dernière modification',
    'LastEditor': 'Dernier éditeur',
    'Status': 'État',
    'Template': 'Modèle',
    'Language': 'Langue',
    'Results': 'Résultats',
    'SortBy': 'Trier par...',
    'View': 'Affichage',
    'TitleAscending': 'Titre (A-Z)',
    'TitleDescending': 'Titre (Z-A)',
    'DateModifiedAscending': 'Date de modification (croissant)',
    'DateModifiedDescending': 'Date de modification (décroissant)',
    'MostRelevant': 'Pertinence',
    'TopicsError': 'Ne pouvais pas charger les sujets depuis le serveur, reessayez dans quelques minutes s\'il vous plaît.  Si ce problème se continue, informez l\'administrateur de system.',
    'QueryError': 'Il n\'y a aucun résultats à cause de l\'indexation en cours, ou le serveur de recherche est en panne ou n\'est pas encore met en place. Si l\'indexation a terminé, informez l\'administrateur de system pour faire installer ou activer le serveur de recherche.',
    'Loading': 'Chargement...',
    'NoResults': 'Aucun résultat',
    'Close': 'Fermer',
    'Status_A': 'Approuvé',
    'Status_O': 'Extrait',
    'Status_I': 'Enregistré',
    'Status_S': 'Soumis pour approbation',
    'Status_M': 'Soumis pour approbation de suppression',
    'Status_P': 'Date de début différée',
    'Status_T': 'En attente d\'achèvement des tâches associées',
    'Status_D': 'En attente de suppression',
    'ViewGrid': 'Quadrillage',
    'ViewTile': 'Carreau',
    'ViewLine': 'Ligne',
    'ResultsMessage': '{0} de {1} résultat',
    'ResultsMessagePlural': '{0} de {1} résultats',
    'NextPageScrollError': 'Ne pouvais pas charger les résultats de recherche suivantes, reessayez dans quelques minutes s\'il vous plaît. Si ce problème se continue, informez l\'administrateur de system.',
    'Filters': 'Filtres',
    'Preview': 'Aperçu',
    'More': 'Plus',
    'PredefinedTopicMy Content': 'Mes contenus',
    'PredefinedTopicAll Content': 'Tous les contenus'
});