define({
    'root': {
        'language': 'Language',
        'taxonomy': 'Taxonomy',
        'author': 'Author',
        'contenttype': 'Content Type',
        'contentsubtype': 'Content Subtype',
        'foldername': 'Folder Name',
        'folderpath': 'Folder Path',
        'tags': 'Tags',
        'xmlconfigid': 'Smart Form ID',
        'selected': 'Selected',
        'unselected': 'Unselected',
        'childSelected': 'Some selected',
        'All': 'All', // referring to filters,
        'contenttype1': 'Content',
        'contenttype2': 'HTML Forms',
        'contenttype3': 'Archive Content',
        'contenttype4': 'Archive Forms',
        'contenttype7': 'Library Image',
        'contenttype8': 'Assets',
        'contenttype9': 'Library Items',
        'contenttype9_vsd': 'Library Microsoft Visio Document',
        'contenttype9_ppt': 'Library Microsoft Power Point Document',
        'contenttype9_mpp': 'Library Microsoft Project Document',
        'contenttype9_pub': 'Library Microsoft Publisher Document',
        'contenttype9_doc': 'Library Microsoft Word Document',
        'contenttype9_xls': 'Library Microsoft Excel Document',
        'contenttype12': 'Archive Multimedia',
        'contenttype101': 'Office Document',
        'contenttype101_vsd': 'Visio Document',
        'contenttype101_ppt': 'Power Point Document',
        'contenttype101_mpp': 'Microsoft Project Document',
        'contenttype101_pub': 'Microsoft Publisher Document',
        'contenttype101_doc': 'Word Document',
        'contenttype101_xls': 'Excel Document',
        'contenttype102': 'PDF Documents',
        'contenttype103': 'Assets',
        'contenttype104': 'Multimedia',
        'contenttype106': 'Images',
        'contenttype1111': 'Discussion Topics',
        'contenttype3333': 'Products',
        'language3076': 'Chinese (Hong Kong)',
        'language5124': 'Chinese (Macao)',
        'language1043': 'Dutch',
        'language3081': 'English (Australia)',
        'language4105': 'English (Canada)',
        'language2057': 'English (U.K.)',
        'language1033': 'English (U.S.)',
        'language1035': 'Finnish',
        'language1036': 'French',
        'language3084': 'French (Canada)',
        'language1031': 'German',
        'language1032': 'Greek',
        'language1040': 'Italian',
        'language1045': 'Polish',
        'language2070': 'Portuguese (Portugal)',
        'language7194': 'Serbian (B. & H. Cyrillic)',
        'language1034': 'Spanish',
        'language2058': 'Spanish (Mexico)',
        'language21514': 'Spanish (U.S.)',
        'language2077': 'Swedish (Finland)'
    },
    'fr': true
});