<%@ Page Title="" Language="C#" MasterPageFile="~/AdminTool/MasterPages/admin.master" AutoEventWireup="true" CodeFile="AllCenterSubscriptions.aspx.cs" Inherits="AdminTool_Templates_AllProfiles" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="mainCPH" Runat="Server">
    <style type="text/css">
        .hidden{
            display:none;
        }
        table th:nth-child(13){
           display:none;
        }
    </style>
    <div>
        <div id="centerInfo" runat="server" visible="false">
            <strong>Name: </strong> <asp:Label ID="lblCenterName" runat="server" /> &nbsp;&nbsp; <strong>Center Id: </strong><asp:Label ID="lblCenterId" runat="server" />
        </div>
        <h3 align="left">Manage All Subscriptions:</h3>            
        <br />       
        <br />
        <asp:GridView ID="GridView1" HeaderStyle-BackColor="#6A6A6A" HeaderStyle-ForeColor="#FE9901" AllowSorting="true" OnSorting="GridView1_Sorting"
            RowStyle-BackColor="#EDEDED" AlternatingRowStyle-BackColor="White" AlternatingRowStyle-ForeColor="#000"
            runat="server" AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="false" PageSize="10" AllowPaging="true" OnPageIndexChanging="OnPageIndexChanging">
            <Columns>               
                <asp:BoundField DataField="FirstName" SortExpression="FirstName" HeaderText="First Name" HeaderStyle-Width="150px" />
                <asp:BoundField DataField="LastName" SortExpression="LastName" HeaderText="Last Name" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="Email" SortExpression="Email" HeaderText="Email" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="OnlineType" SortExpression="OnlineType" HeaderText="Online Type" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="PrintType" SortExpression="PrintType" HeaderText="Print Type" HeaderStyle-Width="150px" />
                <asp:BoundField DataField="Address1" SortExpression="Address1" HeaderText="Address1" HeaderStyle-Width="150px" />
                <asp:BoundField DataField="Address2" SortExpression="Address2" HeaderText="Address2" HeaderStyle-Width="150px" />
                <asp:BoundField DataField="City" SortExpression="City" HeaderText="City" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="State" SortExpression="State" HeaderText="State" HeaderStyle-Width="100px" /> 
                <asp:BoundField DataField="Zipcode" SortExpression="Zipcode" HeaderText="Zip code" HeaderStyle-Width="100px" /> 
                <asp:BoundField DataField="DatePosted" SortExpression="DatePosted" HeaderText="DatePosted" HeaderStyle-Width="100px" /> 
                <asp:BoundField DataField="SubscribtionId" SortExpression="SubscribtionId" ItemStyle-CssClass="hidden" HeaderText="" HeaderStyle-Width="150px" />                                               
            </Columns>
            <EmptyDataTemplate>
                <table cellspacing="0" rules="all" border="0" style="border-collapse: collapse;">
                    <tr style="color: White; background-color: #6A6A6A;">                                             
                        <th scope="col" style="width: 100px;">First Name
                        </th>
                        <th scope="col" style="width: 100px;">Last Name
                        </th>
                        <th scope="col" style="width: 100px;">Email
                        </th>
                        <th scope="col" style="width: 150px;">Online Type
                        </th>
                        <th scope="col" style="width: 150px;">Print Type
                        </th>
                        <th scope="col" style="width: 100px;">Address1
                        </th>
                        <th scope="col" style="width: 100px;">Address2
                        </th>
                        <th scope="col" style="width: 100px;">City
                        </th>                        
                        <th scope="col" style="width: 100px;">State
                        </th>
                        <th scope="col" style="width: 100px;">Zipcode
                        </th>   
                        <th scope="col" style=" display:none;">DatePosted
                        </th>  
                        <th scope="col" style=" display:none;">SubscribtionId
                        </th>                     
                    </tr>
                    <tr>
                        <td colspan="99" align="center">No records found for the search criteria.
                        </td>
                    </tr>
                </table>
            </EmptyDataTemplate>
        </asp:GridView>
    </div>
</asp:Content>

