<%@ Page Title="" Language="C#" MasterPageFile="~/AdminTool/MasterPages/admin.master" AutoEventWireup="true" CodeFile="ManageLanguages.aspx.cs" Inherits="AdminTool_Templates_ManageLanguages" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="mainCPH" Runat="Server">
    <div>
        <h3 align="left">Manage All Langauges</h3>
        <a href="/AdminTool/Templates/AddLanguage.aspx">Add Langauge</a>
        <br />
        <br />
        <br />
        <br />
        <asp:GridView ID="GridView1" HeaderStyle-BackColor="#6A6A6A" HeaderStyle-ForeColor="#FE9901"
            RowStyle-BackColor="#EDEDED" AlternatingRowStyle-BackColor="White" AlternatingRowStyle-ForeColor="#000"
            runat="server" AutoGenerateDeleteButton="False" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="false" PageSize="10" AllowPaging="true" OnPageIndexChanging="OnPageIndexChanging">
            <Columns>               
                <asp:BoundField DataField="LangName" HeaderText="Language Name" HeaderStyle-Width="150px" />
                <asp:BoundField DataField="LangId" HeaderText="Language Id" HeaderStyle-Width="150px" /> 
                <asp:CommandField ShowDeleteButton="True" />                                               
            </Columns>
            <EmptyDataTemplate>
                <table cellspacing="0" rules="all" border="0" style="border-collapse: collapse;">
                    <tr style="color: White; background-color: #6A6A6A;">
                        <th scope="col" style="width: 150px;">Language Name
                        </th>                       
                        <th scope="col" style=" display:none;">LangId
                        </th>                      
                    </tr>
                    <tr>
                        <td colspan="99" align="center">No records found for the search criteria.
                        </td>
                    </tr>
                </table>
            </EmptyDataTemplate>
        </asp:GridView>
    </div>
</asp:Content>

