
if("undefined"===typeof Ektron)
{
    Ektron = {};
}

if("undefined"===typeof Ektron.Widgets)
{
    Ektron.Widgets = {};
}
if("undefined"===typeof Ektron.Widgets.ActivityFeed)
{
    Ektron.Widgets.ActivityFeed = {
        // properties
        id: "",
        clientId: "",
        
        // methods
        Autocomplete: 
        {
            Init: function(id, clientId)
            {
                Ektron.Widgets.ActivityFeed.id = id;
                Ektron.Widgets.ActivityFeed.clientId = clientId;
                
                //alert($ektron('#query').length);
                $ektron('#'+id).inputLabel({
                    cssClass: "ekActivityFilterSearch"
                });
                Ektron.ready(function() {
                    $ektron('#'+id).autocomplete({
                        serviceUrl: 'widgets/ActivityStream/autocomplete.ashx',
                    width: 200,
                        delimiter: /(,|;)\s*/
                            
                    });
                });


                $ektron('#navigation a').each(function() 
                {
                    $ektron(this).click(function(e) 
                    {
                        var element = $ektron(this).attr('href');
                        $ektron('html').animate({scrollTop: $ektron(element).offset().top }, 
                            300, null, function() 
                            {
                                document.location = element; 
                            }
                        );
                        e.preventDefault();
                    });
                });
            }
        },
        bindEvents: function() {
            // this function listens to the move event in the dashboard.
            // It finds the element and matchs it with  the clientid generated by the init function of the widget.
            // then it attaches a postback to the ajax postback thereby making the icallbackeventhandler work.
            
            $ektron(document).bind("EktronPersonalizationSortEnd", function(e, type, ui){
                var sortElement = $ektron(ui);
                var isMe = sortElement.find("input.clientId").attr("value") == Ektron.Widgets.ActivityFeed.clientId ? true : false;
                if ((type == "move") && isMe) {
                    Sys.WebForms.PageRequestManager.getInstance().add_endRequest(Ektron.Widgets.ActivityFeed.moveRefresh);
                }
            });
        },
        Init: function(id, clientId)
        {
            Ektron.Widgets.ActivityFeed.Autocomplete.Init(id, clientId);
            Ektron.Widgets.ActivityFeed.bindEvents();
        },
        moveRefresh: function(){
            __doPostBack('','');
        }     
    }
}




