define({
    'language': 'Langue',
    'taxonomy': 'Taxonomie',
    'author': 'Auteur',
    'contenttype': 'Type de contenu',
    'contentsubtype': 'Sous-type de contenu',
    'foldername': 'Nom du répertoire',
    'folderpath': 'Chemin du répertoire',
    'tags': 'Balises',
    'xmlconfigid': 'ID de Smart Form',
    'selected': 'Sélectionné',
    'unselected': 'Aucun sélectionné',
    'childSelected': 'Quelques sélectionnés',
    'All': 'Tous', // (les filtres)
    'contenttype1': 'Contenus',
    'contenttype2': 'Formulaires HTML',
    'contenttype3': 'Contenus archivé',
    'contenttype4': 'Formulaires HTML archivés',
    'contenttype7': 'Images de bibliothèque',
    'contenttype8': 'Fichiers',
    'contenttype9': 'Éléments de bibliothèque',
    'contenttype9_vsd': 'Documents Visio de bibliothèque',
    'contenttype9_ppt': 'Présentations PowerPoint de bibliothèque',
    'contenttype9_mpp': 'Documents Project de bibliothèque',
    'contenttype9_pub': 'Documents Publisher de bibliothèque',
    'contenttype9_doc': 'Documents Word de bibliothèque',
    'contenttype9_xls': 'Feuilles de calcul Excel de bibliothèque',
    'contenttype12': 'Multimédia archivés',
    'contenttype101': 'Documents Office',
    'contenttype101_vsd': 'Documents Visio',
    'contenttype101_ppt': 'Présentations PowerPoint',
    'contenttype101_mpp': 'Documents Project',
    'contenttype101_pub': 'Documents Publisher',
    'contenttype101_doc': 'Documents Word',
    'contenttype101_xls': 'Feuilles de calcul Excel',
    'contenttype102': 'Documents PDF',
    'contenttype103': 'Fichiers',
    'contenttype104': 'Multimédia',
    'contenttype106': 'Images',
    'contenttype1111': 'Sujets de discussion',
    'contenttype3333': 'Produits',
    'language3076': 'chinois (Hong Kong)',
    'language5124': 'chinois (Macao)',
    'language1043': 'néerlandais',
    'language3081': 'anglais (Australie)',
    'language4105': 'anglais (Canada)',
    'language2057': 'anglais (R.-U.)',
    'language1033': 'anglais (É.-U.)',
    'language1035': 'finnois',
    'language1036': 'français',
    'language3084': 'français (Canada)',
    'language1031': 'allemand',
    'language1032': 'grec',
    'language1040': 'italien',
    'language1045': 'polonais',
    'language2070': 'portugais (Portugal)',
    'language7194': 'serbe (cyrillic B.-H.)',
    'language1034': 'espagnol',
    'language2058': 'espagnol (Mexique)',
    'language21514': 'espagnol (É.-U.)',
    'language2077': 'suédois (Finlande)'
});