<%@ Page Title="" Language="C#" MasterPageFile="~/AdminTool/MasterPages/admin.master" AutoEventWireup="true" CodeFile="Manage-Careers.aspx.cs" Inherits="AdminTool_Templates_Manage_Careers" %>

<asp:Content ID="Content2" ContentPlaceHolderID="mainCPH" runat="Server">
    <style type="text/css">
        .hiddenCareerColumn{
         display:none;
        }
        table th:nth-child(9){
           display:none;
        }
    </style>
    <div>
        <div id="centerInfo" runat="server" visible="false">
            <strong>Name: </strong> <asp:Label ID="lblCenterName" runat="server" /> &nbsp;&nbsp; <strong>Center Id: </strong><asp:Label ID="lblCenterId" runat="server" />
        </div>
        <h3>Manage Careers</h3>
         <a href="/AdminTool/Templates/Career.aspx">Add Career</a>
        <p align="left">This&nbsp;section&nbsp;enables&nbsp;you to&nbsp;add&nbsp;and manage the&nbsp;career&nbsp;postings&nbsp;on your website.</p>
        <ol>
            <li>
                <div align="left">To add a new career post<br/>
                    <br/>
                    <ol>
                        <li type="A">Click on the Add&nbsp;Career link.</li>
                        <li type="A">Select an existing Career Type from the drop-down menu. When an existing Career Type is selected, the system will automatically load the standard job description for that career post. If there is not an existing Career Type that matches your opening, you can enter the type in Alternate Title.</li>
                        <li type="A">If necessary,enter the Alternate Title. The Alternate Title will be displayed on the website with your career post.</li>
                        <li type="A">If desired, you can upload a custom job description.&nbsp;The&nbsp;system&nbsp;supports either&nbsp;a&nbsp;pdf&nbsp;or&nbsp;doc file.&nbsp;</li>
                        <li type="A">Click on Submit to complete the configuration.<br/>
                        </li>
                    </ol>
                </div>
            </li>
            <li>
                <div align="left">To edit an existing career post, click on the Job Post title.<br/>
                </div>
            </li>
            <li>To delete an existing career post, click on the Delete link.</li>
        </ol>
        
        <asp:GridView ID="GridView1" HeaderStyle-BackColor="#6A6A6A" HeaderStyle-ForeColor="#FE9901"
            RowStyle-BackColor="#EDEDED" AlternatingRowStyle-BackColor="White" AlternatingRowStyle-ForeColor="#000"
            runat="server" AutoGenerateDeleteButton="false" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="false" PageSize="10" AllowPaging="true" OnPageIndexChanging="OnPageIndexChanging">
            <Columns> 
                <asp:HyperLinkField DataTextField="Title" DataNavigateUrlFields="JobId"
                    DataNavigateUrlFormatString="/AdminTool/Templates/Career.aspx?jobid={0}" HeaderText ="Title" HeaderStyle-Width="150px" />             
                <asp:BoundField DataField="ProfileType" HeaderText="Career Type" HeaderStyle-Width="150px" />   
                <asp:BoundField DataField="Location" HeaderText="Location" HeaderStyle-Width="150px" />   
                <asp:BoundField DataField="IsPartTime" HeaderText="Is Part Time" HeaderStyle-Width="150px" />   
                <asp:BoundField DataField="IsFullTime" HeaderText="Is Full Time" HeaderStyle-Width="150px" />    
                <asp:BoundField DataField="DatePosted" HeaderText="Date Posted" HeaderStyle-Width="150px" /> 
                <asp:BoundField DataField="DateExpire" HeaderText="Date Expired" HeaderStyle-Width="150px" /> 
                <asp:BoundField DataField="JobId" ItemStyle-CssClass="hiddenCareerColumn" HeaderText="" HeaderStyle-Width="150px" /> 
                <asp:CommandField ShowDeleteButton="True" />                           
            </Columns>
            <EmptyDataTemplate>
                <table cellspacing="0" rules="all" border="0" style="border-collapse: collapse;">
                    <tr style="color: White; background-color: #6A6A6A;">
                        <th scope="col" style="width: 150px;">Title</th>                       
                        <th scope="col" style="width: 150px;">Career Type</th>  
                        <th scope="col" style="width: 150px;">Location</th>                       
                        <th scope="col" style="width: 150px;">Is Part Time</th>
                        <th scope="col" style="width: 150px;">Is Full Time</th>                       
                        <th scope="col" style="width: 150px;">Date Posted</th>    
                        <th scope="col" style="width: 150px;">Date Expired</th>                                        
                    </tr>
                    <tr>
                        <td colspan="99" align="center">No records found for the search criteria.
                        </td>
                    </tr>
                </table>
            </EmptyDataTemplate>
        </asp:GridView>
        <asp:HiddenField ID="hdnCenterId" runat="server" Value="" />
    </div>
</asp:Content>

