<%@ Page Title="" Language="C#" MasterPageFile="~/AdminTool/MasterPages/admin.master" AutoEventWireup="true" CodeFile="manage-all-quotes.aspx.cs" Inherits="AdminTool_Templates_manage_all_quotes" %>

<asp:Content ID="Content2" ContentPlaceHolderID="mainCPH" runat="Server">
    <style type="text/css">
        .hidden{
            display:none;
        }
        table th:nth-child(15){
           display:none;
        }
        .UploadedFileId 
        {
            width:190px;
        }  
        .UploadedFileId a
        {
            display:block;
            word-wrap:normal;
        }
    </style>
    <h3>Manage All Request-A-Quotes</h3>
    <p>File attachments sent through Request-A-Quote are available for download from the server for 30 days. After this time the attached file will be deleted, but the upload history will remain indefinitely.</p>
    <br />
    <div class="AlphabetPager">
        <asp:Repeater ID="rptAlphabets" runat="server">
            <ItemTemplate>
                <asp:LinkButton runat="server" Text='<%#Eval("Value")%>' Visible='<%# !Convert.ToBoolean(Eval("Selected"))%>'
                    OnClick="Alphabet_Click" />
                <asp:Label runat="server" Text='<%#Eval("Value")%>' Visible='<%# Convert.ToBoolean(Eval("Selected"))%>' />
            </ItemTemplate>
        </asp:Repeater>
    </div>
    <br />
    <asp:GridView ID="GridView1" CssClass="centerData" HeaderStyle-BackColor="#6A6A6A" HeaderStyle-ForeColor="#FE9901" AutoGenerateDeleteButton="False"
        RowStyle-BackColor="#EDEDED" AlternatingRowStyle-BackColor="White" AlternatingRowStyle-ForeColor="#000" OnRowDeleting="GridView1_RowDeleting"
        runat="server" AutoGenerateColumns="false" AllowSorting="true" OnSorting="GridView1_Sorting" PageSize="30" AllowPaging="true" OnPageIndexChanging="OnPageIndexChanging">
         <Columns>                         
                <asp:BoundField DataField="FirstName" SortExpression="FirstName" HeaderText="First Name" HeaderStyle-Width="150px" />
                <asp:BoundField DataField="LastName" SortExpression="LastName" HeaderText="Last Name" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="Email" SortExpression="Email" HeaderText="Email" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="JobTitle" SortExpression="JobTitle" HeaderText="Job Title" HeaderStyle-Width="100px" /> 
                <asp:BoundField DataField="CompanyName" SortExpression="CompanyName" HeaderText="Company Name" HeaderStyle-Width="150px" />
                <asp:BoundField DataField="MobileNumber" SortExpression="MobileNumber" HeaderText="Phone Number" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="ProjectName" SortExpression="ProjectName" HeaderText="Project Name" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="ProjectDescription" SortExpression="ProjectDescription" HeaderText="Project Description" HeaderStyle-Width="100px" /> 
                <asp:templatefield HeaderText="Uploaded File(s)" SortExpression="UploadedFileId" ItemStyle-Width="150px" HeaderStyle-Width="150px">
			            <itemtemplate>
				           <div class="UploadedFileId"><%# Eval("UploadedFileId") %></div>
			            </itemtemplate>
		         </asp:templatefield>
                 <asp:TemplateField HeaderText="Download All Files" ItemStyle-Width="100px" HeaderStyle-Width="100px">
                    <ItemTemplate>
                        <div>
                            <a href="/AdminTool/Templates/DownloadZipFiles.aspx?id=<%# Eval("QuoteId") %>&type=raq">Download All Files</a>
                        </div>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="DueDate" SortExpression="DueDate" HeaderText="Due Date" HeaderStyle-Width="150px" DataFormatString="{0:MM/dd/yyyy}" />
                <asp:BoundField DataField="DateSubmitted" SortExpression="DateSubmitted" DataFormatString="{0:MM/dd/yyyy}" HeaderText="Date Submitted" HeaderStyle-Width="150px" />                
                <asp:BoundField DataField="CenterId" SortExpression="CenterId" HeaderText="Center Id" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="QuoteId" ItemStyle-CssClass="hidden" HeaderText="" HeaderStyle-Width="150px" /> 
               <asp:CommandField ShowDeleteButton="True" />                                                
            </Columns>
        <EmptyDataTemplate>
            <table cellspacing="0" rules="all" border="0" style="border-collapse: collapse;">
                 <tr style="color: White; background-color: #6A6A6A;">
                        <th scope="col" style="width: 100px;">First Name
                        </th>
                        <th scope="col" style="width: 100px;">Last Name
                        </th>
                        <th scope="col" style="width: 100px;">Email
                        </th>
                        <th scope="col" style="width: 100px;">Job Title
                        </th>
                        <th scope="col" style="width: 100px;">Company Name
                        </th>               
                        <th scope="col" style="width: 150px;">Phone Number
                        </th>
                        <th scope="col" style="width: 150px;">Project Name
                        </th>
                        <th scope="col" style="width: 100px;">Project Description
                        </th>                          
                        <th scope="col" style=" display:none;">Uploaded File(s)
                        </th> 
                        <th scope="col" style=" display:none;">Download All Files
                        </th>                           
                        <th scope="col" style="width: 150px;">Due Date
                        </th>                                                 
                        <th scope="col" style=" display:none;">Date Submitted
                        </th>  
                         <th scope="col" style="width: 150px;">Center Id
                        </th>              
                    </tr>
                <tr>
                    <td colspan="99" align="center">No records found for the search criteria.
                    </td>
                </tr>
            </table>
        </EmptyDataTemplate>
    </asp:GridView>
</asp:Content>

