define({
    'root': {
        'Search': 'Search',
        'LastModified': 'Last Modified',
        'LastEditor': 'Last Editor',
        'Status': 'Status',
        'Template': 'Template',
        'Language': 'Language',
        'Results': 'Results',
        'SortBy': 'Sort By...',
        'View': 'View',
        'TitleAscending': 'Title (A-Z)',
        'TitleDescending': 'Title (Z-A)',
        'DateModifiedAscending': 'Date Modified (Oldest First)',
        'DateModifiedDescending': 'Date Modified (Most Recent)',
        'MostRelevant': 'Most Relevant',
        'TopicsError': 'Could not load topics from the server, please try again in a few minutes. If this problem continues, contact your system administrator.',
        'QueryError': 'There are no results because indexing is still in progress, or your search server is down or has not been set up. If indexing is complete and you still have no results, contact your system administrator to install or enable your search server.',
        'Loading': 'Loading...',
        'NoResults': 'No results',
        'Close': 'Close',
        'Status_A': 'Approved',
        'Status_O': 'Checked Out',
        'Status_I': 'Checked In',
        'Status_S': 'Submitted for Approval',
        'Status_M': 'Marked for Deletion',
        'Status_P': 'Pending Go Live Date',
        'Status_T': 'Awaiting Completion of Associated Tasks',
        'Status_D': 'Pending Deletion',
        'ViewGrid': 'Grid',
        'ViewTile': 'Tile',
        'ViewLine': 'Line',
        'ResultsMessage': '{0} of {1} result',
        'ResultsMessagePlural': '{0} of {1} results',
        'NextPageScrollError': 'Could not load the next page results from the server, please try again in a few minutes. If this problem continues, contact your system administrator.',
        'Filters': 'Filters',
        'Preview': 'Preview',
        'More': 'More',
        'PredefinedTopicMy Content': 'My Content',
        'PredefinedTopicAll Content': 'All Content'
    },
    'fr': true
});