<%@ Page Title="" Language="C#" MasterPageFile="~/AdminTool/MasterPages/admin.master" AutoEventWireup="true" CodeFile="AllCenterConsultationRequests.aspx.cs" Inherits="AdminTool_Templates_AllCenterConsultationRequests" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="mainCPH" Runat="Server">
    <style type="text/css">
        .hidden{
            display:none;
        }
        table th:nth-child(10){
           display:none;
        }
    </style>
    <div>
        <div id="centerInfo" runat="server" visible="false">
            <strong>Name: </strong> <asp:Label ID="lblCenterName" runat="server" /> &nbsp;&nbsp; <strong>Business Id: </strong><asp:Label ID="lblCenterId" runat="server" />
        </div>
        <h3 align="left">Manage All Consultation Requests:</h3>            
        <br />       
        <br />
        <asp:GridView ID="GridView1" HeaderStyle-BackColor="#6A6A6A" HeaderStyle-ForeColor="#FE9901" AllowSorting="true" OnSorting="GridView1_Sorting"
            RowStyle-BackColor="#EDEDED" AlternatingRowStyle-BackColor="White" AlternatingRowStyle-ForeColor="#000"
            runat="server" AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="false" PageSize="10" AllowPaging="true" OnPageIndexChanging="OnPageIndexChanging">
            <Columns>               
                <asp:BoundField DataField="FirstName" SortExpression="FirstName" HeaderText="First Name" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="LastName" SortExpression="LastName" HeaderText="Last Name" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="Email" SortExpression="Email" HeaderText="Email" HeaderStyle-Width="150px" />
                <asp:BoundField DataField="Company" SortExpression="Company" HeaderText="Company" HeaderStyle-Width="100px" />
                <asp:BoundField DataField="Phone" SortExpression="Phone" HeaderText="Phone" HeaderStyle-Width="100px" /> 
                <asp:BoundField DataField="DatePosted" SortExpression="DatePosted" HeaderText="Date Posted" HeaderStyle-Width="100px" /> 
                <asp:BoundField DataField="IsSignupChecked" SortExpression="IsSignupChecked" HeaderText="Marketing opt-in?" HeaderStyle-Width="100px" /> 
                <asp:BoundField DataField="HowCanWeHelp" SortExpression="HowCanWeHelp" HeaderText="How Can We Help?" HeaderStyle-Width="150px" />   
                 <asp:BoundField DataField="ConsultationRequestId" SortExpression="ConsultationRequestId" ItemStyle-CssClass="hidden" HeaderText="" HeaderStyle-Width="150px" />                                               
            </Columns>
            <EmptyDataTemplate>
                <table cellspacing="0" rules="all" border="0" style="border-collapse: collapse;">
                    <tr style="color: White; background-color: #6A6A6A;">                                             
                        <th scope="col" style="width: 100px;">First Name
                        </th>
                        <th scope="col" style="width: 100px;">Last Name
                        </th>
                        <th scope="col" style="width: 100px;">Email
                        </th>
                        <th scope="col" style="width: 100px;">Company
                        </th>
                        <th scope="col" style="width: 100px;">Phone
                        </th>  
                        <th scope="col" style=" display:none;">DatePosted
                        </th>  
                        <th scope="col" style=" display:none;">ConsultationRequestId
                        </th>                     
                    </tr>
                    <tr>
                        <td colspan="99" align="center">No records found for the search criteria.
                        </td>
                    </tr>
                </table>
            </EmptyDataTemplate>
        </asp:GridView>
    </div>
</asp:Content>

